# オープンサイエンス {#OpenScience}

\index{open science}

*Chapter lead: Kees van Bochove* 

OHDSI創立当時から今までOHDSIコミュニティの目的は、オープンソースソフトウェアの使用や、すべての会議の手続きや資料の公共的供給と生産された医学的根拠の透明公開アクセスのようにオープンサイエンスの価値を構築することにより、国際的な協力体系を構築することだった。しかし、オープンソースソフトウェアとは正確に何を言うかそしてOHDSIがどのように個人情報保護に非常に敏感で、一般的に良い意図だけでは入手できない医療データのオープンデータ戦略やオープンサイエンス戦略を構築することができただろうか？なぜ分析の再現性を持つことが非常に重要なのか？そしてOHDSIコミュニティはどのようにこの目標を達成しようとするか？これは、私たちがこの章で扱う問題のいくつかである。

## オープンサイエンス

「オープンサイエンス（Open Science）」という用語は、90年代から使用されてきた。しかし、OHDSIが生まれ、2010年代から牽引力を得るために始めた。ウィキペディア[@wiki：Open_science]は、この用語の意味を「科学研究（出版物、データ、実際のサンプルおよびソフトウェアを含む）を作成して社会的、アマチュアや専門家のすべてのレベルでのアクセスを伝播する運動」と定義しており、さらに一般的には、共同ネットワークを介して開発されると言う。 OHDSIコミュニティは自主的に「オープンサイエンス」集団あるいはネットワークと定義していなかったが、この用語は、OHDSIの概念と原則を使用するのによく使用される。例えば、2015年Jon DukeはOHDSIを「医療基づい生成に関するオープンサイエンスのアプローチ "[^ 1]と言うし、2019年にはEHDENコンソーシアムの入門用ウェブセミナーでは、OHDSIネットワークアプローチを「21世紀の現実世界のオープンサイエンス」[ ^ 2]と絶賛した。この章で見るようになりつつありが、オープンサイエンスの多くの実行は、今日のOHDSIコミュニティで発見されることができる。いくつかのOHDSIコミュニティは、医療根拠作成の透明性と信頼性を改善するための共同のニーズによって開始された草の根のオープンサイエンス集団と主張している。

オープンサイエンスまたは「サイエンス2.0 "[@wiki：Science_2.0]アプローチは、現在の医学界の慣行で認識された様々な問題を解決するものである。情報技術は、データの生成と解析方法の爆発的な増加に続き、個々の研究の場合専門分野に発表されたすべての文献を追いつくが非常に難しい。特に普段診療日をしながら、最新の医学に遅れをとらないようにする臨床医の場合は、はるかにそうである。さらに、多くの実験が劣悪な統計デザイン、偏向パブリケーション、p-hackingと同様の統計的問題に影響を受けており、再現するのは難しいの懸念が高まっている。これらの懸念を矯正するための従来の方法である出版された論文のPeer reviewでは、このような問題を見つけて解決することができない。 2018年Natureの特集号で「再現できない研究の難しさ "[^ 3]は、いくつかの例を示した。した著者のグループは、自分たちが属している分野の論文で体系的文献考察を適用しようとしたが、様々な理由で、識別された論文のエラーを修正するのは難しいことを発見した。特に欠陥のあるデザインで始めた実験では、特に修正するのは難しい。 Ronald Fisherの言葉によると、「実験を終えた後、統計学者に相談することは、まるで彼に死体解剖をしてほしいというようなものです。おそらく何のために、その実験が死亡したのかは教えてくれるでしょう。」 [@wikiquote：Ronald_Fisher]著者は、統計的意味やメタ分析の誤った計算は、不適切なベースラインの比較に関連する誤った結論を導くれる欠陥ランダム実験設計などの統計的な問題をよく出会う。 [@ allison_2016]物理学の経験を例にとると、同じコレクションの別の論文では、基本的なデータを利用することができるように提供するだけでなく、データの処理と解析のコピーを出版して、適切な記録文書に作成十分再現を試みるようにすること重要であると主張している. [@Chen2018]

OHDSIコミュニティは、これらの困難に対して自主的に解決し、大規模な医学根拠を作ることが重要であることに重点を置いている。 SchuemieとRyanなどが@ schuemie_2018bで述べたように現在のパラダイムは、「未知の信頼性と、一度に1つの推定値を発表することができるユニークな実験設計を介して、一度に1つの推定値を生成することに重点を置いて "いるが、 OHDSIコミュニティは一貫して、標準化された方法を使用して、大規模な処理を通じた観察研究を支持し、評価、修正、および偏見のない結果を発表し、より信頼性の高い完全な根拠基盤を作ることができる。これは、データをOMOP CDMにマッピングする医療データソースネットワークと、すべての人が利用することができ証明できるオープンソースの分析コードを、また、howoftten.orgで発表した疾患発生に関する大規模な基準データを組み合わせて実現することができる。次の段落では、具体的な例を示し、オープンスタンダード、オープンソース、公開データ、オープン談話の4つの原則を利用して、OHDSIのオープンサイエンスのアプローチをより詳細に説明する。この章では、オープンサイエンスの観点からOHDSIの公平な原則と展望について簡単に参考にしたものに仕上げている。

## 実践のオープンサイエンス: Study-a-Thon

\index{study-a-thon}

コミュニティ内の最近の動向は、「Study-a-thons」の出現である。 Study-a-thonとOMOPデータモデルとOHDSIツールを使用して、重要で臨床的に関連がある研究の質問に答えるために、複数の学問分野にわたる科学者が集まって、短く集中対面会議をする集まりである。これに関する良い例は、EHDENウェビナーで説明2018 Oxford study-a-thonのに、プロセスを段階的に提供して公開されている結果を強調している。 Study-a-thonに続く期間の間、参加者は医学的に関連のある研究テーマを提案して複数の研究テーマは、study-a-thon自体が行われている間、研究されるように選ばれる。 OMOP形式の患者レベルのデータにアクセスすることができ、これらのデータソースに抽出条件を作成することができます参加者を介してデータが提供される。実際study-a-thon時間のほとんどは、統計的アプローチ（\ @ref（WhereToBegin）章参照）、データソースの適合性、相互作用で作られた結果とこれらの結果により、必然的に提起されたフォローアップの質問を議論するために使用されている。 Oxford study-a-thonの場合、様々な膝置換手術後に発生する副作用の研究を中心に質問が行われOHDSIフォーラムとtoolを利用して、study-a-thonが進行中対話的に結果を発表した。 （\ @ref（OhdsiAnalyticsTools）章を参照）ATLASのようなOHDSI toolはコホート定義の迅速な作成、交換、ディスカッション、および評価を容易にして、問題の定義と方法の選択の合意に到達する最初のプロセスを非常に迅速に加速してくれる。関連データソースとOHDSIオープンソースの患者レベル予測（patient level prediction）パッケージ\ @ref（PatientLevelPrediction）の使い勝手のおかげで、一日に手術後90日の死亡率の予測モデルを作成し、次の日、複数の大規模なデータソースからのモデルの外部検証が可能だった。また、study-a-thonは、伝統的な学術論文（膝関節全形成副作用のpatient-levelの予測モデルの開発と検証、Ross Williams、Daniel Prieto-Alhambra et al。、論文作成中）を作り出した、Peer reviewを通って進行された場合、数ヶ月かかった作業である。しかし、数億人の患者の記録を扱う多数の医療データベースの解析スクリプトと結果が1週間以内に落書きのようなドラフトから設計、生産、出版されたという事実は、OHDSIが根拠を作るのに必要な処理期間を数か月から数日で減少させて医療分野を根本的に向上させることができるということを見せてくれる。

[^edhenWebinarUrl]: https://youtu.be/X5yuoJoL6xs

## オープンスタンダード

\index{open science!open standards}

OHDSIコミュニティで維持管理されている非常に重要なコミュニティのリソースはOMOP共通のデータモデル（\ @ref（CommonDataModel）章を参照）と関連用語（\ @ref（StandardizedVocabularies）章を参照）である。モデル自体は観察医療データを収集するために範囲が定めれ、元のは、薬物、手術、医療機器などにさらされているとの診断と検査のような結果との間の関連性を分析するためのものであった、今、様々な分析ユースケースに拡張された。 （\ @ref（DataAnalyticsUseCases）章を参照）が、様々なコーディングシステム、医療パラダイム、様々な種類の医療ソースの世界の医療データを統一させるには、ソースコードに最も近い標準化され用語間の膨大な量の「マッピング」が必要である。 OMOP一般的な用語は、\ @ref（DataAnalyticsUseCases）の章でさらに説明する。 OMOP一般的な用語は、世界中で使用されている何百もの医療コーディングシステムとのマッピングを含んでおりOHDSI Athenaツールを使用して閲覧することができる。これらのvocabularyとマッピングを自由に利用可能なリソースにコミュニティに提供により、OMOPとOHDSIコミュニティは、医療データの分析に多大な貢献をしており、いくつかのいくつかの研究者によると、この目的のための最も包括的なモデルであり、全世界で約12億人の医療記録を代表している。[^ 6] [@ garza_2016]  - （翻訳注：最近の調査データによると、約21億人、アメリカを除く約3億8千万人の材料。機関間材料が連携されないため患者のデータが難しかっ回重複済み起因含まれている実際の固有の患者数に比べて、よりたくさん評価さ）

## オープンソース

\index{open science!open source}

OHDSIコミュニティが提供するもう一つの重要なリソースは、オープンソースのプログラムである。ここでは、データをOMOPにマッピングするためのヘルパーツール（\ @ref（ExtractTransformLoad）章参照）は、一般的に使用される強力な統計的手法を含むOHDSIメソッドライブラリ、公開された観察研究のためのオープンソースコードを、OHDSI ecosystemを裏付けるするATLAS、Athena、その他のインフラ関連のソフトウェア（\ @ref（OhdsiAnalyticsTools）章を参照）に分けることができる。オープンサイエンスの観点から、最も重要なリソースの一つは、OHDSI研究ネットワークのような実際の研究を実行するためのコードである。 （\ @ref（NetworkResearch）章を参照）その次には、このプログラムは、GitHubを通じて点検、検討および寄与が可能な完全なオープンソースのOHDSIスタックを活用する。たとえば、ネットワークの研究は、分析法の使用例の統計的方法を一貫して再利用することができるライブラリをベースにしている場合が多い。 OHDSIのオープンソースソフトウェアの使用と協力が生成された根拠に対する品質と信頼性をどのように裏付けているかについての詳細概要は、\ @ref（SoftwareValidity）章を参照してください。

## 公開データ

\index{open science!open data}

個人情報保護に敏感な医療データの特性のために完全開放的かつ包括的なpatient-levelのデータセットは、一般的に使用することができない。しかし、前述したhttp://howoften.orgとhttp://data.ohdsi.orgに投稿された他の公開の結果セットとの重要な集計データや結果セットを公開するためにOMOPマップされたデータセットを活用するのは可能である。また、OHDSIコミュニティは、テストと開発のためにSynPUFのようなシミュレーションのデータセットを提供し、OMOPにマッピングされて利用可能なデータソースのネットワークの中での研究を行うためにOHDSI研究ネットワーク（\ @ref（NetworkResearch）章を参照）が使用することができる。ソースデータとOMOP CDMとの間のマッピングを透明するためにしたマッピングのために、データソースがOHDSI ETLまたは「マッピング」ツールを再利用し、マッピングのコードをオープンソースとしても公開することが望ましい。また、OHDSIコミュニティは、テストと開発の目的でSynPUFのようなシミュレーションされたデータ・セットを提供しOHDSIリサーチネットワークを活用して、データをOMOPにマッピングした使用可能なデータソースのネットワークで研究を実行することができる。ソースデータとOMOP CDMとの間のマッピングを明瞭にするためにOHDSI ETLまたは「マッピング」ツールを再利用すると同時に、マッピングのコードをオープンソースとして公開するのがよい。

## 開かれた談話

\index{open science!open discourse}

オープンスタンダード、オープンソース、公開データは、優れた資産であるが、それ自体では診療行為に大きな影響はないだろう。 OHDSIのオープンサイエンス活動と影響の核心は、医学的根拠の生成を実装して、科学から診療現場へと移行するようにしてくれるだろう。 OHDSIコミュニティは、アメリカ、ヨーロッパ、アジアで開催されるいくつかの年次OHDSIシンポジウムをはじめ、特に中国と韓国の献身的に実践するコミュニティを保有している。これらのシンポジウムでは、統計的方法、データ、およびソフトウェア・ツールの使用方法、一般的な用語は、OHDSIオープンソースコミュニティの他のすべての面での発展について議論する。 OHDSIフォーラム[^ 8]とウィキ[^ 9]は、全世界の数千人の研究者が観察研究を行うように助ける。コミュニティリモート会議[^ 10]とGitHub [^ 11]のコードを、問題、pull requestsは、コード、CDMのようなオープンコミュニティの資産を継続して発展させOHDSIネットワーク研究では、全世界的に数億個の患者の記録を利用して、開放かつ透明な方法で世界的観察研究が行われている。開放性と開かれた談話は、コミュニティ全体に推奨されてすぐに、この本は、OHDSIウィキ、コミュニティリモート会議、GitHub repositoryによって促進されるオープンプロセスを介して使われる。 [^ 12]しかし、OHDSI共同研究者たちがいない場合は、プロセスとツールは、空の殻になることを強調する必要がある。実際OHDSIコミュニティの真の価値は、\ @ref（OhdsiCommunity）の章で説明したように協力とオープンサイエンスを通じて健康を増進するというビジョンを共有しているメンバーと一緒にすると言うことができる。 

## OHDSIとFAIRのガイド原則

\index{FAIR}

### 導入

이 장의 마지막 단락은 @wilkinson2016 이 발표한 FAIR 데이터 가이드 원칙을 사용하여 OHDSI 커뮤니티와 도구의 현재 상태를 살펴본다.

###	検索性\

OMOPにマッピングされて分析に使用されているすべての医療データベースは、科学的な観点から、将来の参照と再現性のために持続しなければならない。 OMOPデータベースのための永続的な識別子を使用することがまだ広く普及されることはなかった、部分的には、これらのデータベースがファイアウォールの背後に含まれているか、内部ネットワークにおいて、インターネットに必ず接続されていないからである。しかし、引用の目的のように参照することができる説明の記録では、データベースの要約を掲載することは完全に可能である。この方法は、EMIFカタログ11の例に従い、このカタログは、データ収集目的、ソース、vocabularyと用語、アクセス制御メカニズム、ライセンス、同意などの面で、データベースへの総合的な記録を提供する。 [@ Oliveira2019]このアプローチは、IMI EHDENプロジェクトでさらに詳細な開​​発された。

###	アクセシビリティ

オープンプロトコルを介してOMOPにマッピングされたデータは、通常、SQLインタフェースを介して行われるが、このインタフェースは、OMOP CDMと結合してOMOPデータにアクセスするための標準化されて文書化された方法を提供する。しかし、上で説明したように、OMOPソースは、セキュリティ上の理由から、インターネットを介して直接利用することができない場合が多い。 IMI EHDENのようなプロジェクトの活発な研究テーマとオペレーティング目標は研究者がアクセスすることができる安全な世界の医療データネットワークを作成するものである。しかし、LEGENDとhttp://howoften.orgのようなOHDSI取り組みを通じて示すよう、多数のOMOPデータベースの分析結果を一般に公開することができる。

###	相互運用性

相互運用性（Interoperability）は、間違いなくOMOPデータモデルとOHDSIツールの強力な利点である。根拠の生成のために活用することができる、世界的に強力な医療データソースのネットワークを構築するためには、医療データソースとの間の相互運用性を達成することが重要であり、これはOMOPモデルと標準用語集（Standardized Vocabularies）を介して達成される。しかし、コホート定義と統計的アプローチを共有することにより、OHDSIコミュニティは、コードのマッピングを超え、医療データの分析方法の相互運用可能な理解を作成するためのプラットフォームを提供する。病院などの医療システムは、多くの場合、OMOPデータの記録のソースであるため、OHDSIアプローチの相互運用性は、HL7 FHIR、HL7 CIMIとOpenEHRのオペレーティング的な医療の相互運用性の標準と一致することにより、さらに向上させることができる。 CDISCや生物医学オントロジーのような臨床的な相互運用性の標準との整列も同じだ。特に腫瘍学の分野でこれは重要なテーマであり、OHDSIコミュニティのOncology Working GroupとClinical Trials Working Groupは、このような問題が、積極的に議論されているフォーラムの良い例を示している。他のデータの参照と、特にオントロジー用語の面では、ATLASとOHDSI Athenaは、他の利用可能な医療コーディングシステムの文脈でOMOP標準用語集を閲覧することができますので、重要なツールである。

### 再利用の可能性

再利用性（Reusability）に関するFAIR原則は、データライセンス、ソース（データがどのように存在していることの明確化）と関連コミュニティ標準との接続などの重要な問題に焦点を当てている。データのライセンスは、複雑なトピックとしては、特に管轄区域で、より複雑であり、広範囲に扱うには、この本の範囲外である。しかし、あなたのデータ（例えば、分析結果）を他のユーザーが自由に使用できるようにしたい場合は、データのライセンスを使用して、これらの権限を明示的に提供するのがよい。しかし、まだインターネット上で見つけることができるほとんどのデータの一般的な慣行ではなく、残念ながらOHDSIコミュニティも例外ではない。 OMOPデータベースのデータソースに関連して、CDMバージョンでは、標準的な用語集の配布は、カスタムコードのリストなどの自動化された方法でメタデータを使用できるようにするために、潜在的に改善すべき点が存在する。 OHDSI ETLツールは、現在、この情報を自動的に生成していませんが、Data Quality Working GroupとMetadata Working Groupのようなワークグループは、これに対して活発に作業中である。もう一つの重要な側面は、基本的なデータベース自体のソースを検証である。病院や一般の用情報システムが交換されたか、または変更されたか、そして知られているデータの欠落やその他のデータの問題は、過去にいつ発生したかを知ることが重要である。 OMOP CDMで、これらのメタデータを体系的に接続する方法をナビゲートすることがMetadata Working Groupの領域である。

``` {block2, type='rmdsummary'}
- OHDSIコミュニティは、医療根拠生成の相互運用性と再現性を積極的に追求するオープンサイエンスコミュニティに見ることができる。

- 従来の単一の研究と、単一の推定医学研究のパラダイムでは、実世界の医療材料を利用して、基礎発生率のような事実を知らせ、仲裁と治療の効果を統計的に推定する根拠を、大規模なと体系的に生成するパラダイムへの転換を支持してている。 

```

[^1]: https://www.ohdsi.org/wp-content/uploads/2014/07/ARM-OHDSI_Duke.pdf
[^2]: https://www.ehden.eu/webinars/
[^3]: https://www.nature.com/collections/prbfkwmwvz
[^6]: https://www.ema.europa.eu/en/events/common-data-model-europe-why-which-how
[^7]: https://emif-catalogue.eu
[^8]: https://forums.ohdsi.org
[^9]: https://www.ohdsi.org/web/wiki
[^10]: https://www.ohdsi.org/web/wiki/doku.php?id=projects:overview
[^11]: https://github.com/ohdsi
[^12]: https://github.com/OHDSI/TheBookOfOhdsi

